name: sunshine_spotter
description: "Uncover your next adventure with ease – this intuitive app helps you find sunny spots and exciting destinations nearby, all with just a few taps and no complicated coordinates!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  geolocator: ^13.0.4
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
