repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        pass_filenames: false
        args: ["--config-file", "mypy.ini", "--explicit-package-bases", "Backend"]
        additional_dependencies:
          - "types-requests==2.32.0.20240905"
          - "types-redis"

