[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["Backend"]
filterwarnings = [
  "ignore::DeprecationWarning:fastapi.*",
  "ignore::DeprecationWarning:starlette.*",
]
addopts = "--timeout=30 --timeout-method=thread --showlocals"
