name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CACHE_REFRESH_SYNC: 'true'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.11'
    - name: Install dependencies (runtime + dev)
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        elif [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        else
          echo "No requirements file found (requirements.txt or requirements-dev.txt)" && exit 1
        fi
    - name: Run ruff check
      run: ruff check .
    - name: Run mypy
      run: mypy .
    - name: Run tests
      run: pytest -q
    - name: Run security audit
      run: pip-audit --desc
      continue-on-error: true
