name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CACHE_REFRESH_SYNC: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run ETag invariance quick checks
        run: |
          pytest Backend/tests/test_etag_invariance.py Backend/tests/test_etag_roundtrip.py -q
        # Fail fast if ETag regressions introduced
      - name: Run tests with coverage
        run: pytest --cov=Backend --cov-report=xml:coverage.xml -q
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: false
      - name: Run security audit
        run: pip-audit --desc
        continue-on-error: true
