name: Deploy to Cloud Run (staging)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      GCP_PROJECT: sun-chaser-081623
      GCP_REGION: us-west1
      CLOUD_RUN_SERVICE: sun-chaser-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Build (Cloud Build)
        run: |
          gcloud builds submit --tag gcr.io/${GCP_PROJECT}/${CLOUD_RUN_SERVICE}:staging .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${CLOUD_RUN_SERVICE} \
            --image gcr.io/${GCP_PROJECT}/${CLOUD_RUN_SERVICE}:staging \
            --platform managed \
            --region ${GCP_REGION} \
            --allow-unauthenticated \
            --set-env-vars MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }},CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }},ENABLE_Q=true,TELEMETRY_SINK_URL=${{ secrets.TELEMETRY_SINK_URL }}

      - name: Smoke test
        run: |
          URL=$(gcloud run services describe ${CLOUD_RUN_SERVICE} --region=${GCP_REGION} --format='value(status.url)')
          echo "URL: $URL"
          curl -fsS "$URL/health"
          curl -fsS "$URL/metrics" | head -n 10
