---
name: Flutter CI — analyze & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: |
          cd Frontend
          flutter pub get
      - name: Analyze
        run: |
          cd Frontend
          flutter analyze --no-fatal-warnings --no-fatal-infos
      - name: Run tests
        run: |
          cd Frontend
          flutter test --coverage
      - name: Web build (smoke)
        run: |
          cd Frontend
          flutter build web --release
