name: Flutter CI

on:
  push:
  pull_request:

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test --no-pub

      - name: Check for frontend app
        id: check_frontend
        run: |
          if [ -f "lib/main.dart" ]; then
            echo "has_app=true" >> $GITHUB_OUTPUT
          else
            echo "has_app=false" >> $GITHUB_OUTPUT
          fi

      - name: Build web (optional)
        if: steps.check_frontend.outputs.has_app == 'true'
        run: flutter build web --release
        continue-on-error: true
