name: Integration - Dedupe Matrix

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, feature/unsplash-tracking ]

jobs:
  dedupe-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dedupe-ttl: [0.5, 1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server (uvicorn)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          # Start server in background
          nohup .venv/bin/uvicorn main:app --port 8000 &

      - name: Run integration smoke (dedupe TTL matrix)
        env:
          BASE_URL: ${{ secrets.SMOKE_BASE_URL }}
          UNSPLASH_TEST_HEADER_SECRET: ${{ secrets.UNSPLASH_TEST_HEADER_SECRET }}
        run: |
          # If running against a deployed staging instance, BASE_URL should be provided.
          BASE=${{ secrets.SMOKE_BASE_URL }}
          if [ -z "$BASE" ]; then
            BASE="http://127.0.0.1:8000"
          fi
          python Backend/scripts/integration_smoke.py --base-url "$BASE" --photo-id "ci-matrix-${{ matrix.dedupe-ttl }}" --mock-trigger --dedupe-ttl ${{ matrix.dedupe-ttl }}

  concurrency-check:
    runs-on: ubuntu-latest
    needs: dedupe-matrix
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server (uvicorn)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          nohup .venv/bin/uvicorn main:app --port 8000 &

      - name: Run concurrency probe
        env:
          BASE_URL: ${{ secrets.SMOKE_BASE_URL }}
          UNSPLASH_TEST_HEADER_SECRET: ${{ secrets.UNSPLASH_TEST_HEADER_SECRET }}
        run: |
          BASE=${{ secrets.SMOKE_BASE_URL }}
          if [ -z "$BASE" ]; then
            BASE="http://127.0.0.1:8000"
          fi
          python Backend/scripts/concurrency_probe.py
