name: Integration smoke

on:
  pull_request:
    paths:
      - 'Backend/**'
      - 'docs/**'
      - '.github/workflows/**'

jobs:
  integration-smoke:
    runs-on: ubuntu-latest
    env:
      ALLOW_TEST_HEADERS: 'true'
      UNSPLASH_TEST_HEADER_SECRET: ${{ secrets.UNSPLASH_TEST_HEADER_SECRET }}
      UNSPLASH_CLIENT_ID: ${{ secrets.UNSPLASH_CLIENT_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI server
      run: |
        # Start uvicorn in background; logs will show in the job log
        nohup python -m uvicorn Backend.main:app --host 127.0.0.1 --port 8000 &
        sleep 1

    - name: Wait for server readiness
      run: |
        echo "Waiting for FastAPI to become ready..."
        url="http://127.0.0.1:8000/internal/photos/meta?photo_id=ci-smoke"
        ok=1
        for i in {1..12}; do
          status=$(curl -s -o /dev/null -w "%{http_code}" "$url" || echo "000")
          echo "Attempt $i: status=$status"
          if [ "$status" = "200" ]; then
            ok=0
            break
          fi
          sleep 2
        done
        if [ "$ok" -ne 0 ]; then
          echo "Server did not become ready in time" >&2
          exit 1
        fi

    - name: Run integration smoke
      run: |
        python Backend/scripts/integration_smoke.py --base-url http://127.0.0.1:8000 --photo-id ci-smoke --mock-trigger --wait
